services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234567
    ports:
      - "3307:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - wetech-network

  backend:
    build:
      context: ./backend-spring-wetech
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234567
      JWT_SECRET: secret-very-strong-key-here
      CLOUDINARY_CLOUD_NAME: CLOUDINARY_CLOUD_NAME_TEST
      CLOUDINARY_API_KEY: CLOUDINARY_API_KEY_TEST
      CLOUDINARY_API_SECRET: CLOUDINARY_API_SECRET_TEST
    ports:
      - "8080:8080"
    networks:
      - wetech-network

  frontend:
    build:
      context: ./frontend-wetech
      dockerfile: Dockerfile
      args:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - wetech-network

networks:
  wetech-network:
    driver: bridge
