version: '3.8'

services:
  backend:
    build:
      context: ./backend-spring-wetech
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://<POSTGRES_HOST>:<POSTGRES_PORT>/<POSTGRES_DB>
      SPRING_DATASOURCE_USERNAME: <POSTGRES_USER>
      SPRING_DATASOURCE_PASSWORD: <POSTGRES_PASSWORD>
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    networks:
      - wetech-network

  frontend:
    build:
      context: ./frontend-wetech
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - wetech-network

networks:
  wetech-network:
    driver: bridge
